import 'package:instagram/model/user_data.dart';

List<UserData> userDataList = [
  UserData(
    name: "Alice Johnson",
    imageUrl: "assets/img/alice.png",
    posts: "Check out my latest painting!",
    likes: 350,
    comments: 45,
    shared: 10,
    avatar: "https://pict.ai/images/secure/mvgWJ3/jRBW2mIVyYTboIB_1727461558.png",
  ),
  UserData(
    name: "Bob Smith",
    imageUrl: "assets/img/bob.png",
    posts: "A quick snapshot from my morning run.",
    likes: 200,
    comments: 30,
    shared: 5,
    avatar: "https://static.vecteezy.com/system/resources/previews/035/647/628/non_2x/ai-generated-man-athlete-flexing-muscle-isolated-on-transparent-background-free-png.png",
  ),
  UserData(
    name: "Charlie Brown",
    imageUrl: "assets/img/charlie.png",
    posts: "Finally completed my art project, feeling accomplished!",
    likes: 500,
    comments: 100,
    shared: 20,
    avatar: "https://cdn.lucidpic.com/cdn-cgi/image/w=600,format=auto,metadata=none/66e2f656da519.png",
  ),
  UserData(
    name: "Diana Green",
    imageUrl: "assets/img/diana.png",
    posts: "A snapshot from my weekend getaway to the mountains.",
    likes: 150,
    comments: 25,
    shared: 3,
    avatar: "https://cdn.lucidpic.com/cdn-cgi/image/w=600,format=auto,metadata=none/66c43929de4e6.png",
  ),
  UserData(
    name: "Eva White",
    imageUrl: "assets/img/eva.png",
    posts: "Exploring the beautiful landscapes of New Zealand.",
    likes: 800,
    comments: 200,
    shared: 50,
    avatar: "https://cdn.lucidpic.com/cdn-cgi/image/w=600,format=auto,metadata=none/66e3080f2a0ec.png",
  ),
  UserData(
    name: "Frank Black",
    imageUrl: "assets/img/franck.png",
    posts: "Loving the new album by my favorite band!",
    likes: 120,
    comments: 20,
    shared: 8,
    avatar: "https://static.vecteezy.com/system/resources/previews/028/597/531/non_2x/standing-man-cartoon-avatar-character-full-body-ai-generated-file-no-background-png.png",
  ),
  UserData(
    name: "Grace Lee",
    imageUrl: "assets/img/grace.png",
    posts: "Here's my travel diary from my recent trip to Italy!",
    likes: 220,
    comments: 15,
    shared: 12,
    avatar: "https://img.freepik.com/premium-psd/latin-woman-smiling_1187-27326.jpg",
  ),
  UserData(
    name: "Hannah Blue",
    imageUrl: "assets/img/hanna.png",
    posts: "Trying out some new recipes in the kitchen today.",
    likes: 670,
    comments: 90,
    shared: 30,
    avatar: "https://img.freepik.com/premium-psd/positive-laughing-girl-smiling-camera-wearing-white-tee-transparent-background_265339-2241.jpg",
  ),
  UserData(
    name: "Ian Gold",
    imageUrl: "assets/img/ian.png",
    posts: "Had a great time hiking with friends this weekend!",
    likes: 350,
    comments: 60,
    shared: 10,
    avatar: "https://png.pngtree.com/png-vector/20240131/ourmid/pngtree-business-man-illustration-ai-generative-png-image_11578835.png",
  ),
  UserData(
    name: "Jenna Red",
    imageUrl: "assets/img/jena.png",
    posts: "Just finished reading an amazing book on quantum mechanics.",
    likes: 450,
    comments: 75,
    shared: 18,
    avatar: "https://photoai.com/cdn-cgi/image/format=jpeg,fit=cover,width=1024,height=1536,quality=85/https://r2-us-west.photoai.com/1714355577-4ebc34cdd400e36b207740ab6655ffcc-4.png",
  ),
];
